### ISSUE TITLE
Отсутствие "Keymap Report" в меню

### ISSUE THREAD

**Issue by ur4ltz** [kvichans/cuda_keys_report#3]
После обновления  пункт "Keymap Report" не появлся в меню.
В "plugins.json" он есть..

Что не так?..

**Comment by ur4ltz** [comment]
Вот мой  plugins.json

{
  "commands" : {
    "cuda_sess_manager" : {
      "04" : {
        "proc" : "saveAs",
        "caption" : "Session Manager\Save session as..."
      },
      "01" : {
        "proc" : "open",
        "caption" : "Session Manager\Open\/New session..."
      },
      "00" : {
        "proc" : "recent",
        "caption" : "Session Manager\Recent sessions..."
      },
      "03" : {
        "proc" : "save",
        "caption" : "Session Manager\Save session"
      },
      "02" : {
        "proc" : "openPrev",
        "caption" : "Session Manager\Open previous session"
      }
    },
    "cuda_html_preview" : {
      "00" : {
        "lexers" : "HTML,HTML_,PHP,PHP_",
        "proc" : "run",
        "caption" : "HTML Preview"
      }
    },
    "cuda_devdocs" : {
      "01" : {
        "proc" : "run_text",
        "caption" : "DevDocs\Search by text"
      },
      "00" : {
        "proc" : "run_input",
        "caption" : "DevDocs\Search by input"
      }
    },
    "cuda_addonman" : {
      "2" : {
        "proc" : "do_remove",
        "caption" : "Addons Manager\Remove plugin..."
      },
      "0" : {
        "proc" : "do_install_addon",
        "caption" : "Addons Manager\Install..."
      },
      "1" : {
        "proc" : "do_edit",
        "caption" : "Addons Manager\Edit plugin..."
      },
      "3" : {
        "proc" : "do_download_all",
        "caption" : "Addons Manager\Download all..."
      },
      "4" : {
        "proc" : "do_config",
        "caption" : "Addons Manager\Config..."
      }
    },
    "cuda_markdown_preview" : {
      "00" : {
        "lexers" : "Markdown",
        "proc" : "run",
        "caption" : "Markdown Preview"
      }
    },
    "cuda_keymap_report" : {
      "00" : {
        "proc" : "run",
        "caption" : "Keymap Report"
      }
    },
    "cuda_backup_file" : {
      "00" : {
        "proc" : "run",
        "caption" : "Backup File"
      }
    },
    "cuda_switch_header" : {
      "00" : {
        "proc" : "run",
        "caption" : "Switch Header"
      }
    },
    "cuda_insert_time" : {
      "0" : {
        "proc" : "run",
        "caption" : "Insert Time"
      }
    },
    "cuda_make_plugin" : {
      "0" : {
        "proc" : "run",
        "caption" : "Make Plugin"
      }
    }
  }
}

**Comment by Alexey-T** [comment]
новая Куд- plugins.json not used anymore. П-ты в Plugins у меня есть (2шт.)
